services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: market-hub!
      MYSQL_DATABASE: market-hub
      MYSQL_USER: market-hub-user
      MYSQL_PASSWORD: market-hub!
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
